Update qhimm.xml
tsunamods-codes/7th-Heaven-Catalogs pull request #206
Opened 2024-11-19 15:09 UTC by bradhowlett

Here is my retry on doing this correct. The only thing I don't quite understand is the whole iros/GDrive linking methodology.

2024-11-19 18:09 UTC, julianxhokaxhiu requested changes
Minor changes required but you're on the right track. Please do no open another PR, just update this one instead. Thank you!

2024-11-19 18:09 UTC, julianxhokaxhiu commented on catalogs/qhimm.xml
> +      <Link>https://drive.google.com/file/d/1iwfYEec-eu6K4hB6zD06dok1jH92lX3n/view?usp=drive_link</Link>
The link on this tag should be like where you want your users need to go to know more about your mod, not the download link.

2024-11-19 18:09 UTC, julianxhokaxhiu commented on catalogs/qhimm.xml
> +        <Link></Link>
Here instead the download link should be put, but instead with this syntax: `iros://GDrive/ID` where ID is the unique UUID drive gives you after `/d/`

2024-11-19 18:09 UTC, julianxhokaxhiu commented on catalogs/qhimm.xml
> +        <DownloadSize>419</DownloadSize>
This should be in KB ( just open up an explorer window in Windows and put the same number it gives you in KB )

2024-11-19 20:29 UTC, bradhowlett commented
> Minor changes required but you're on the right track. Please do no open another PR, just update this one instead. Thank you!

I cannot find where to go to edit my request?

2024-11-19 21:40 UTC, bradhowlett commented
> This could be one way: https://docs.github.com/en/codespaces/the-githubdev-web-based-editor#opening-the-githubdev-editor

Ok. i believe I fixed it. I am not 100% positive my link to my file and my ID are correct but I am sure you will let me know

2024-11-19 21:44 UTC, bradhowlett commented
Sorry I accidentally created another pull but I closed it

2024-11-20 10:29 UTC, julianxhokaxhiu commented
Closing in favor of #207 - Your changes have been reflected there, not here. But please next time, find some time to learn a bit how to contribute properly :) Thank you

2024-11-20 10:29 UTC, closed without merging